#!/usr/bin/env python
import random

characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

def randchar():
    return random.choice(characters)

def randcomp():
    return randchar() + randchar() + randchar()

print(randcomp() + "-" + randcomp() + "-" + randcomp() + "-" + randcomp())
